minio:
  endpoint: ${MINIO_ENDPOINT}
  region_name: ${MINIO_REGION}
  access_key: ${MINIO_ROOT_USER}
  secret_key: ${MINIO_ROOT_PASSWORD}
  secure: false

buckets:
  landing: ${S3_BUCKET_LANDING}
  formatted: ${S3_BUCKET_FORMATTED}
  trusted: ${S3_BUCKET_TRUSTED}

chroma:
  persist_directory: ${CHROMADB_DIR}
  collections:
    images: images_embeddings
    texts: texts_embeddings
    clip_mm: clip_multimodal
